// database.js

// Updated weaponDatabase, containing your full list of weapons and damages:
const weaponDatabase = [
  { name: "Bow and Arrow", damage: "7/5/–" },
  { name: "Black powder pistol", damage: "7/3/6" },
  { name: "Crossbow", damage: "7/4/6" },
  { name: "Musket", damage: "8/5/6" },
  { name: "American Derringer Mini-Cop", damage: "11/1/6" },
  { name: "AMT Automag v", damage: "12/3/5" },
  { name: "Auto-ordnance pit Bull", damage: "10/1/4" },
  { name: "Beretta 92FS Centurion", damage: "10/2/3" },
  { name: "Beretta Model 21 Bobcat", damage: "8/1/4" },
  { name: "Beretta Model 950BS Jet Fire", damage: "8/1/4" },
  { name: "Beretta M9", damage: "10/2/3" },
  { name: "Browning Hi-power", damage: "10/2/3" },
  { name: "Colt Delta Elite MKIv Series 80", damage: "11/2/4" },
  { name: "Colt 380 Gov't pocketlite", damage: "8/1/4" },
  { name: "Colt 1911A", damage: "10/2/4" },
  { name: "CZ 75B", damage: "10/1/3" },
  { name: "Desert Eagle .357 Magnum", damage: "11/3/3" },
  { name: "Desert Eagle .50AE", damage: "12/3/4" },
  { name: "E.T. \"Series one Laseraim\"", damage: "11/3/3" },
  { name: "Glock 17", damage: "10/1/3" },
  { name: "Glock 18", damage: "10/1/3; 10/2/1" },
  { name: "Grendel p-12", damage: "9/1/3" },
  { name: "Grendel p-30", damage: "8/1/1" },
  { name: "Heckler & Koch p7", damage: "10/2/4" },
  { name: "Heckler & Koch HK45C", damage: "10/2/3" },
  { name: "Kahr K9", damage: "10/1/4" },
  { name: "Intratec Tec-9", damage: "10/3/1" },
  { name: "Intratec Tec-22", damage: "8/2/1" },
  { name: "Kimber Solo Carry", damage: "10/1/6" },
  { name: "Llama Large Frame", damage: "10/2/4" },
  { name: "Makarov", damage: "10/2/4" },
  { name: "Norinco Type M1911", damage: "10/3/4" },
  { name: "Norinco Tokarev", damage: "10/2/4" },
  { name: "ruger p89", damage: "10/2/3" },
  { name: "Sig-Sauer p-220", damage: "10/2/4" },
  { name: "Smith & Wesson 2213 Sportsman", damage: "8/1/4" },
  { name: "Smith & Wesson 3566", damage: "11/3/3" },
  { name: "Smith & Wesson Sigma", damage: "10/1/3" },
  { name: "Walther p-5 Compact", damage: "10/1/4" },
  { name: "Walther ppK", damage: "9/1/5" },
  { name: "Chiappa rhino", damage: "12/3/5" },
  { name: "Colt Detective Special", damage: "9/1/5" },
  { name: "Colt King Cobra", damage: "11/3/5" },
  { name: "rossi Model 515", damage: "8/2/4" },
  { name: "rossi Model 851", damage: "9/2/5" },
  { name: "S&W Model 19 Combat Magnum", damage: "11/2/5" },
  { name: "Smith & Wesson Model 500", damage: "12/3/5" },
  { name: "Taurus Model 85", damage: "9/2/5" },
  { name: "Thompson Center Arms Contender", damage: "12/3/6" },
  { name: "Beretta M12", damage: "10/5/6" },
  { name: "FN p90", damage: "13/5/6" },
  { name: "Colt M6351", damage: "10/5/1" },
  { name: "Hechler & Koch Mp5", damage: "10/5/1" },
  { name: "Heckler & Koch Mp5 K", damage: "10/3/1" },
  { name: "Heckler & Koch Mp5 police", damage: "11/5/1" },
  { name: "Heckler & Koch Mp7", damage: "12/5/1" },
  { name: "Heckler & Koch uMp", damage: "11/5/1" },
  { name: "Mp40", damage: "10/5/1" },
  { name: "M3", damage: "10/5/1" },
  { name: "Mini uZI", damage: "10/3/1" },
  { name: "ruger Mp9", damage: "10/3/1" },
  { name: "TDI vector", damage: "11/5/2" },
  { name: "Thompson M1A1", damage: "10/5/1" },
  { name: "uZI", damage: "10/4/1" },
  { name: "Amsel Striker", damage: "13/4/3" },
  { name: "Benelli 121", damage: "13/5/4" },
  { name: "Benelli 90 M3", damage: "13/5/4" },
  { name: "Beretta 1201 riot", damage: "13/5/5" },
  { name: "Bernadelli", damage: "13/5/3" },
  { name: "Franchi SpAS-12", damage: "13/5/4" },
  { name: "Mossberg Special purpose", damage: "13/5/4" },
  { name: "Remington 870 police", damage: "13/5/4" },
  { name: "Ruger red Label", damage: "10/5/6" },
  { name: "Winchester Model 1300 Marine", damage: "13/5/4" },
  { name: "AK-47", damage: "13/5/1" },
  { name: "AK-74", damage: "13/5/1" },
  { name: "K2", damage: "13/4/1" },
  { name: "FN F2000", damage: "13/5/1" },
  { name: "M16", damage: "13/5/1" },
  { name: "M14", damage: "13/5/2" },
  { name: "SvD Dragunov", damage: "13/5/3" },
  { name: "Tavor TAr-21", damage: "13/5/1" },
  { name: "Winchester Model 70", damage: "12/5/5" }
];

// Existing schtickDatabase remains the same:
const schtickDatabase = [
  "Headshot: After a successful attack, foe may decide that hero takes –2 penalty to skill checks until beginning of subsequent fight. Usable once per fight.",
  "Pedal to the Metal [Driving]: When driving as the pursuer in a chase, gain +2 Driving if one or more PC drivers have fewer Chase Points.",
  "Ram-Alama-Bam [Driving]: When driving, if foe rams a vehicle, gains +2 Frame. +4 Damage Value when foe hits a pedestrian.",
  "Be the Shield: Spend 1 shot to lower bodyguard’s Defense by 2, increasing ally’s Defense by 2, until bodyguard goes down.",
  "Shibuya Slide [Driving]: When driving as the evader in a chase, gain +2 Driving if one or more PC drivers have fewer Cha
